### ISSUE TITLE
Preemptible VMs

### ISSUE THREAD

**Issue by AppOrchestra** [jerryjj/gitlab-runner-gce#1]
Thanks for the awesome script, I'll be trying it out sometime in the next few weeks.

One suggestion as an option to document is the --preemptible flag, which then costs 20% of the standard price, at the risk of the VM being shutdown prematurely, and after 24hrs at most.
https://cloud.google.com/compute/docs/instances/create-start-preemptible-instance

**Comment by jerryjj** [comment]
Hopefully it helps :)

Yeah, I have to copy the note I added to the Blog article about the Preemptible VMs to the repo README.
Also the Worker nodes will be teared down automatically after one hour (by default), so the 24 hour limit will not be reached.
Of course this can be configured by modifying the default configs/shared-sa.toml file.

**Comment by jerryjj** [comment]
Added note about usage of Preemptible VMS to the README.
Thanks for the comment!

**Comment by AppOrchestra** [comment]
No worries, I see you already had the flag in the runner script, I was just looking at the gloud command in the readme. Now I understand that there's a runner that spawns workers you wouldn't necessarily want preemptible on the worker
